apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod111
  name: pod111
spec:
  imagePullSecrets:
   - name: ashusec
  containers:
  - image: ashutoshh.azurecr.io/web
    name: pod111
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
