apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: ashudep1
  name: ashudep1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ashudep1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ashudep1
    spec:
      containers:
      - image: dockerashu/ashuciscowebapp:v202
        name: ashuciscowebapp
        env:
         - name: x   # name of varibale 
           value: web2  # value of varible  but this only for this deployment 
        ports:
         - containerPort: 80
        resources: {}
status: {}
