apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod10
  name: pod10
  namespace: ashutoshh
spec:
  volumes:
   - name: ashuvolpvc
     persistentVolumeClaim:
      claimName: ashuclaim
  containers:
  - image: nginx
    name: pod10
    volumeMounts:
     - name: ashuvolpvc
       mountPath:  /usr/share/nginx/html/
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
