apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: storagepod1
  name: storagepod1
spec:
  nodeName: ip-172-31-95-51.ec2.internal   # i want to schedule pod here only
  volumes:  #  this volume will be created  when we run this yaml 
   - name: ashuvol22
     hostPath:
      path: /var/run/docker.sock
      type: Socket
  containers:
  - image: portainer/portainer
    name: storagepod1
    ports:
     - containerPort: 9000
    volumeMounts:   # mounting voluem 
     - name: ashuvol22
       mountPath: /var/run/docker.sock  #  mount path can be anylocation with in the POD 
