apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ashuclaim
  namespace: ashutoshh  #  personal namespace 
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
  storageClassName: slow
