apiVersion: v1
kind: ReplicationController
metadata:
  creationTimestamp: null
  labels:
    run: ashwebpod
  name: myrc1  #name of rc 
spec:
  replicas: 3  # pod count 
  templates:
   metadata:
    name: mypods
    labels:
     x: helloapp
   spec:
    containers:
     - image: dockerashu/ashuciscowebapp:v202
       name: ashwebpod
       ports:
        - containerPort: 80
 
