apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: ashusvc55
  name: ashusvc3   # name of  servcie  
spec:
  ports:
  - name: "80"
    port: 80   # manadotary option   port  number of  service IP 
    protocol: TCP
    targetPort: 80   #  pod  port  number 
  selector:                # here we have to write  same label as  pod  label
    run: ashwebpod33   #label of pod
  type: NodePort
status:
  loadBalancer: {}
