apiVersion: v1
kind: Pod
metadata:
 name: ashupod1   #  make sure you have unique podname 
spec:
 containers:
  - name: ashuc1    #  this name can be same for all
    image: alpine
    command: ["/bin/sh","-c","ping google.com"]  # this will be replacing entrypoint data for docker image
