apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null   # we can write  creation time 
  labels:         #  
    run: ashupod3
  name: ashupod3   # name of pod
spec:
  containers:
  - image: nginx
    name: ashupod3
    resources: {}     # we can define ram and cpu consumption like cgroups in docker 
  dnsPolicy: ClusterFirst   #  optional
  restartPolicy: Never  #  optional 
