FROM  nginx
MAINTAINER  ashutoshh@linux.com
COPY  app1  /usr/share/nginx/html/
#  /usr/share/nginx/html is the default locaiton for NGINX to read data 
EXPOSE  80
#  default port  of web server that container can use 
